### ISSUE TITLE
You blow out the competition, and I think you can do it faster

### ISSUE THREAD

**Issue by dvanlunen** [w201rdada/portfolio-Intersect1734#3]
This is a great idea and a very convincing pitch. I love how you show the image from the Garmin app and then images of the suggestions from your idea. When I read the Garmin app’s screen I immediately thought it wasn’t helpful—that advice could be given to any person in any place and solutions that aren’t tailored rarely work. Your suggestions are much more personalized and take multiple angles at convincing people to do more they give the person a reason why to be active. It’s also cool that you have a reach goal to have the app suggest new things too. 

My one suggestion is: try and make it a little shorter. For example, though the paragraph describing the average user serves a purpose, it doesn’t have the punch that the rest of the pitch does. 

Great job! I’d get this app just to find things to do haha

**Comment by Intersect1734** [comment]
Thanks for the advice. That part did feel a little clumsy. I went back and redid the flow. After the w201 study of storytelling, I made it more personal and gave it a beginning, middle, and end. (I'm still getting used to being allowed to say "I" in academic writing, too :P ) Hopefully that makes each sentence feel like it contributes something.

Thanks for the feedback!
