### ISSUE TITLE
Comments on Project 2: Fitbit meets Meetup

### ISSUE THREAD

**Issue by Michael-Diamond-Data** [w201rdada/portfolio-Intersect1734#6]
I really like the idea of a) making exercise more fun, and b) bringing a social element into the process.  The are of "experience" - both experience design and experiential marketing does seem to be very "of the moment" right now, as companies try to deepen their engagement with consumers, and consumers are looking for more meaningful interactions with their "stuff".   This idea really has "legs" as they would say ... seems to me there might also be a whole host of 'virtuous' pursuits, including some that are socially useful that could deliver the sort of exercise opportunities you would be looking for.   I'm thinking of things like working for Habitat for Humanity etc on a weekend, which can often be a real workout at the same time that it is delivering important social value. 

I'm reflecting too that your app might provide the service of a truly "holistic" counsellor - perhaps talking to all the other apps - to poll them about what they are saying, and trying to bring it together in a more holistic picture.

One thing I'm curious about, is the importance of getting all the elements right, or at least in balance i.e., diet, exercise, sleep, mindfulness, work/life balance etc.   If you're app could provide this richer context - and help folks understand that its much a balance - as it is getting "top marks" in any one area.

Fantastic set of questions ... wouldn't it be great if .....  our technology was more human, and more helpful at the same time!!!

**Comment by Intersect1734** [comment]
I like the idea of the 'workout' suggestions being themed. Habitat for Humanity could be an option, if someone indicates that social work is important to them. For someone else who indicates that their children are important, perhaps a corn maze or playground. I'll think more on what sorts of data we could collect to really find these personalized activities - beyond just distance.

I do want to be wary of taking on too much in one app, though, so i think sleep, work/life balance, etc will fall to a different app to analyze!

Thanks for the feedback!
